<?php
/** @var $this Company_Authors_Block_Author */
?>
<?php
 $blockProductList = Mage::app()->getLayout()->createBlock('catalog/product_list');
 $author = Mage::getResourceModel('Company_authors/authors_collection');
 $author->addFieldToSelect('author_description');
 $author->addFieldToSelect('name');
 $author->addFieldToFilter('name', Mage::registry('authorName'));
 $data = $author->getData();
 $_description = $data[0]['author_description'];
?>
<div class="content-right">
<section class="numbers-list-section">
<div class="label-info label-info-main">
        <h1 class="as-label"><?php echo Mage::registry('authorName'); ?></h1>
        <?php echo $this->getChildHtml('toolbar_only'); ?>
</div>
<?php if($_description): ?>
        <div class="category-description std">
            <?php echo $_description; ?>
        </div>
<?php endif; ?>
<style type="text/css">
   .price {margin-bottom: 5px !important;}
</style>
<div class="numbers-list">
    <?php
        $_productCollection=$this->getAllProductsOfAuthor();
        $_helper = Mage::helper('catalog/output');
    ?>
    <?php if(!$_productCollection->count()): ?>
      <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
    <?php else: ?>
    <div class="category-products">
        
    <?php $_collectionSize = $_productCollection->count() ?>
        
        <?php foreach ($_productCollection as $_product): ?>

            <div class="single-edition-product <?php if( $_product->getTypeId() == 'simple' ): ?>simple-product<?php endif;?>" data-title="<?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?>" style="width: 163px; margin: 0px 17px 40px;" >
                <figure>
                   <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(163); ?>" width="163" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
                </figure>
                <h3 class="small-headings"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h3>
                <sCompanyn class="info"><?php echo $_product->getCompanySubtitle() ?></sCompanyn>

                <div class="wrapper-row">
                    <div class="left" style="width:126px">
                      
                        <?php echo $blockProductList->getPriceHtml($_product, true) ?>
                      
                    </div>

                    <?php if($_product->isSaleable()): ?>
                        
                        <a href="<?php echo $blockProductList->getAddToCartUrl($_product) ?>" class="ico-link add-to-cart " title="<?php echo Mage::helper('core')->quoteEscape($this->__('Add to Cart')) ?>">
                            <?php echo Mage::helper('divante_configurator')->getSvg('icon-cart') ?>
                            </a>
                        
                    <?php else: ?>
                        <p class="availability out-of-stock"><sCompanyn><?php echo $this->__('Out of stock') ?></sCompanyn></p>
                    <?php endif; ?>

                </div>
            </div>

        <?php endforeach ?>
        <script type="text/javascript">decorateList('products-list', 'none-recursive')</script>

    </div>
    <?php endif; ?>
</div>

</section>
</div>


